services:
  - type: web
    name: surprise
    runtime: node
    plan: free
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
